spring:
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_JDBC_URL_ARCHIVE:jdbc:postgresql://localhost:5433/archive}
    username: postgres
    password: password

  personal-datasource:
    jdbc-url: ${SPRING_DATASOURCE_JDBC_URL_PERSONAL:jdbc:postgresql://localhost:5434/personal}
    username: postgres
    password: password

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_schema: requests

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

